In [15]:
import pandas as pd

data1 = 'data/QLD-2015-19-student-attendance-rate-by-school.csv'

data2 = 'data/QLD-School-Directory.csv'

df1 = pd.read_csv(data1)
df2 = pd.read_csv(data2)

In [36]:
df1

,School Code,School,Attendance Year,School Type,School Category,Remoteness Area,Region,Local Government Area,State Electorate,FTE Days Attended,Possible Attendance Days,Attendance Rate
0,591,Abercorn State School,2015,State School,Primary,Outer Regional Australia,Central Queensland,North Burnett (R),Callide,1987.5,2103.0,94.50%
1,591,Abercorn State School,2016,State School,Primary,Outer Regional Australia,Central Queensland,North Burnett (R),Callide,1632.5,1705.0,95.70%
2,591,Abercorn State School,2017,State School,Primary,Outer Regional Australia,Central Queensland,North Burnett (R),Callide,1405.0,1440.0,97.60%
3,591,Abercorn State School,2018,State School,Primary,Outer Regional Australia,Central Queensland,North Burnett (R),Callide,1640.0,1700.0,96.50%
4,591,Abercorn State School,2019,State School,Primary,Outer Regional Australia,Central Queensland,North Burnett (R),Callide,1657.5,1728.0,95.90%
...,...,...,...,...,...,...,...,...,...,...,...,...
6127,275,Zillmere State School,2015,State School,Primary,Major Cities of Australia,Metropolitan,Brisbane (C),Aspley,11786.0,12919.0,91.20%
6128,275,Zillmere State School,2016,State School,Primary,Major Cities of Australia,Metropolitan,Brisbane (C),Aspley,12816.5,13956.0,91.80%
6129,275,Zillmere State School,2017,State School,Primary,Major Cities of Australia,Metropolitan,Brisbane (C),Aspley,11195.0,12314.0,90.90%
6130,275,Zillmere State School,2018,State School,Primary,Major Cities of Australia,Metropolitan,Brisbane (C),Aspley,12004.0,13503.0,88.90%
6131,275,Zillmere State School,2019,State School,Primary,Major Cities of Australia,Metropolitan,Brisbane (C),Aspley,10843.5,12567.0,86.30%

In [44]:
df1['School Code'].value_counts()

3057    5
1221    5
2147    5
1927    5
1119    5
       ..
A109    2
A068    2
146     1
912     1
A657    1
Name: School Code, Length: 1237, dtype: int64

In [48]:
df2

,Centre Code,Centre Name,Centre Type,Centre Status,Host Centre Code,Host Centre Name,Official Low Year Level,Official High Year Level,Officer In Charge Title,School Band,...,Statistical Area Level2 Code,Remoteness Area,Enrolment Effective Date,All Student Count,Campus All Student Count,ABN,Sector,Non-State Sector,Longitude,Latitude
0,5817,A B Paterson College (Arundel),Non-State School,Open,NaN,NaN,Prep Year,Year 12,Principal,NaN,...,309031235,Major Cities of Australia,NaN,NaN,NaN,NaN,Non-State,Independent,153.360364,-27.927672
1,591,Abercorn State School,State School,Open,NaN,NaN,Prep Year,Year 6,Principal,5.0,...,319021508,Outer Regional Australia,2019 July,18.0,NaN,2.210125e+10,State,NaN,151.127031,-25.135955
2,1275,Abergowrie State School,State School,Open,NaN,NaN,Prep Year,Year 6,Principal,5.0,...,318011465,Remote Australia,2019 July,4.0,NaN,8.724407e+10,State,NaN,145.883510,-18.474697
3,5588,Aboriginal & Islander Independent Community Sc...,Non-State School,Open,NaN,NaN,Prep Year,Year 12,Principal,NaN,...,303051076,Major Cities of Australia,NaN,NaN,NaN,NaN,Non-State,Independent,153.025757,-27.581562
4,25,Acacia Ridge State School,State School,Open,NaN,NaN,Early Childhood,Year 6,Principal,8.0,...,303051076,Major Cities of Australia,2019 July,379.0,NaN,9.928509e+10,State,NaN,153.016074,-27.579554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1769,2367,Youth and Community Learning Centre (Toowoomba),Non-State School,Open,NaN,NaN,Year 8,Year 12,Principal,NaN,...,317011454,Inner Regional Australia,NaN,NaN,NaN,NaN,Non-State,Catholic,151.955281,-27.533144
1770,1954,Yugumbir State School,State School,Open,NaN,NaN,Prep Year,Year 6,Principal,11.0,...,311031319,Major Cities of Australia,2019 July,1089.0,NaN,6.145468e+10,State,NaN,153.049445,-27.675902
1771,372,Yuleba State School,State School,Open,NaN,NaN,Early Childhood,Year 6,Principal,5.0,...,307011177,Remote Australia,2019 July,15.0,NaN,9.632736e+10,State,NaN,149.381988,-26.614533
1772,1002,Yungaburra State School,State School,Open,NaN,NaN,Prep Year,Year 6,Principal,7.0,...,306051169,Outer Regional Australia,2019 July,205.0,NaN,3.915362e+10,State,NaN,145.585798,-17.272953
1773,275,Zillmere State School,State School,Open,NaN,NaN,Prep Year,Year 6,Principal,6.0,...,302041046,Major Cities of Australia,2019 July,130.0,NaN,3.745681e+10,State,NaN,153.037355,-27.364673

In [18]:
df2.columns

Index(['Centre Code', 'Centre Name', 'Centre Type', 'Centre Status',
       'Host Centre Code', 'Host Centre Name', 'Official Low Year Level',
       'Official High Year Level', 'Officer In Charge Title', 'School Band',
       'Show Holiday Date', 'Internet Site', 'Phone Number',
       'Restrict Contact Outside Teaching Hours', 'Fax Number',
       'Actual Address Line 1', 'Actual Address Line 2',
       'Actual Address Line 3', 'Actual Address Post Code',
       'Postal Address Line 1', 'Postal Address Line 2',
       'Postal Address Line 3', 'Postal Address Post Code',
       'Education Geographic Region', 'Federal Electorate', 'State Electorate',
       'Local Government Area', 'Statistical Area Level2',
       'Statistical Area Level2 Code', 'Remoteness Area',
       'Enrolment Effective Date', 'All Student Count',
       'Campus All Student Count', 'ABN', 'Sector', 'Non-State Sector',
       'Longitude', 'Latitude'],
      dtype='object')

In [30]:
df3 = pd2.loc[:,['Centre Code', 
       'Official Low Year Level',
       'Official High Year Level',
       'Actual Address Line 3', 'Actual Address Post Code',
       'All Student Count',
       'Longitude', 'Latitude']].dropna()




df3 = df3.rename(columns = {'Centre Code':'School Code','Actual Address Line 3':'Suburb','Actual Address Post Code':'Post Code'})

df3

,School Code,Official Low Year Level,Official High Year Level,Suburb,Post Code,All Student Count,Longitude,Latitude
1,591,Prep Year,Year 6,Abercorn,4627,18.0,151.127031,-25.135955
2,1275,Prep Year,Year 6,Abergowrie,4850,4.0,145.883510,-18.474697
4,25,Early Childhood,Year 6,Acacia Ridge,4110,379.0,153.016074,-27.579554
5,1983,Prep Year,Year 6,Agnes Water,4677,222.0,151.910560,-24.213972
6,598,Prep Year,Year 6,Airville,4807,11.0,147.347629,-19.655190
...,...,...,...,...,...,...,...,...
1767,757,Prep Year,Year 6,Yorkeys Knob,4878,277.0,145.722722,-16.814268
1770,1954,Prep Year,Year 6,Regents Park,4118,1089.0,153.049445,-27.675902
1771,372,Early Childhood,Year 6,Yuleba,4427,15.0,149.381988,-26.614533
1772,1002,Prep Year,Year 6,Yungaburra,4884,205.0,145.585798,-17.272953
1773,275,Prep Year,Year 6,Zillmere,4034,130.0,153.037355,-27.364673

In [54]:
df3['School Code'].value_counts()

3057    1
1565    1
996     1
276     1
1730    1
       ..
1888    1
2166    1
1214    1
5180    1
649     1
Name: School Code, Length: 1237, dtype: int64

In [1]:
df5 = pd.merge(df1,df3,on = 'School Code',how='inner')

df5['School Code'].value_counts()

NameError: name 'pd' is not defined

In [58]:
df5.to_csv('data/cleaned_data_schoolattendancerate.csv',index=False,header=True)